name: conditional-workflow
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: github.repository == 'Vnuuk/actions-test'
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run: echo "Goodbye Moon!"
