name: conditional-workflow
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: github.repository == 'octo-org/octo-repo-prod'
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run: echo "Goodbye Moon!"
