on:
  push:
    - main
    - dev
  pull_request:
    - main

jobs:
  hellow_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: |
          echo "REF: $GITHUB_REF"
          echo "JOB ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"